=== DILCISBoard/SIARD/SIARD 2.0/format/2015-10-27/table0.xsd
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<xs:schema 
  xmlns:xs="http://www.w3.org/2001/XMLSchema" 
  xmlns="http://www.admin.ch/xmlns/siard/2.0/schema0/table0.xsd" 
  attributeFormDefault="unqualified" 
  elementFormDefault="qualified" 
  targetNamespace="http://www.admin.ch/xmlns/siard/2.0/schema0/table0.xsd">
  <xs:element name="table">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="0" name="row" type="rowType"></xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="rowType">
    <xs:sequence>
      <xs:element minOccurs="0" name= "c1" type="xs:boolean" /> <!-- CBOOLEAN -->
      <xs:element minOccurs="0" name= "c2" type="xs:hexBinary" /> <!-- CBIT -->
      <xs:element minOccurs="0" name= "c3" type="xs:hexBinary" /> <!-- CBIT_32 -->
      <xs:element minOccurs="0" name= "c4" type="xs:hexBinary" /> <!-- CBIT_VARYING_160 -->
      <xs:element minOccurs="0" name= "c5" type="xs:hexBinary" /> <!-- CBINARY -->
      <xs:element minOccurs="0" name= "c6" type="xs:hexBinary" /> <!-- CBINARY_5 -->
      <xs:element minOccurs="0" name= "c7" type="xs:hexBinary" /> <!-- CBINARY_VARYING_32 -->
      <xs:element minOccurs="0" name= "c8" type="blobType" /> <!-- CBINARY_LARGE_OBJECT -->
      <xs:element               name= "c9" type="xs:string" /> <!-- CCHARACTER -->
      <xs:element minOccurs="0" name="c10" type="xs:string" /> <!-- CCHARACTER_5 -->
      <xs:element minOccurs="0" name="c11" type="xs:string" /> <!-- CCHARACTER_VARYING_32 -->
      <xs:element minOccurs="0" name="c12" type="clobType" /> <!-- CCHARACTER_LARGE_OBJECT -->
      <xs:element minOccurs="0" name="c13" type="xs:string" /> <!-- CNATIONAL_CHARACTER -->
      <xs:element minOccurs="0" name="c14" type="xs:string" /> <!-- CNATIONAL_CHARACTER_5 -->
      <xs:element minOccurs="0" name="c15" type="xs:string" /> <!-- CNATIONAL_CHARACTER_VARYING_32 -->
      <xs:element minOccurs="0" name="c16" type="clobType" /> <!-- CNATIONAL_CHARACTER_LARGE_OBJECT -->
      <xs:element minOccurs="0" name="c17" type="clobType" /> <!-- CXML -->
      <xs:element minOccurs="0" name="c18" type="xs:integer" /> <!-- CSMALLINT -->
      <xs:element               name="c19" type="xs:integer" /> <!-- CINTEGER -->
      <xs:element minOccurs="0" name="c20" type="xs:integer" /> <!-- CBIGINT -->
      <xs:element minOccurs="0" name="c21" type="xs:decimal" /> <!-- CDECIMAL -->
      <xs:element minOccurs="0" name="c22" type="xs:decimal" /> <!-- CDECIMAL_3 -->
      <xs:element minOccurs="0" name="c23" type="xs:decimal" /> <!-- CDECIMAL_5_2 -->
      <xs:element minOccurs="0" name="c24" type="xs:decimal" /> <!-- CNUMERIC -->
      <xs:element minOccurs="0" name="c25" type="xs:decimal" /> <!-- CNUMERIC_3 -->
      <xs:element minOccurs="0" name="c26" type="xs:decimal" /> <!-- CNUMERIC_5_2 -->
      <xs:element minOccurs="0" name="c27" type="xs:float" /> <!-- CREAL -->
      <xs:element minOccurs="0" name="c28" type="xs:float" /> <!-- CFLOAT -->
      <xs:element minOccurs="0" name="c29" type="xs:float" /> <!-- CFLOAT_13 -->
      <xs:element minOccurs="0" name="c30" type="xs:float" /> <!-- CDOUBLE_PRECISION -->
      <xs:element minOccurs="0" name="c31" type="dateType" /> <!-- CDATE -->
      <xs:element minOccurs="0" name="c32" type="xs:time" /> <!-- CTIME -->
      <xs:element minOccurs="0" name="c33" type="xs:time" /> <!-- CTIME_5 -->
      <xs:element minOccurs="0" name="c34" type="dateTimeType" /> <!-- CTIMESTAMP -->
      <xs:element minOccurs="0" name="c35" type="dateTimeType" /> <!-- CTIMESTAMP_7 -->
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="clobType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="file" type="xs:anyURI" />
        <xs:attribute name="length" type="xs:integer" />
        <xs:attribute name="digestType" type="digestTypeType" />
        <xs:attribute name="messageDigest" type="xs:string"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="blobType">
    <xs:simpleContent>
      <xs:extension base="xs:hexBinary">
        <xs:attribute name="file" type="xs:anyURI" />
        <xs:attribute name="length" type="xs:integer" />
        <xs:attribute name="digestType" type="digestTypeType" />
        <xs:attribute name="messageDigest" type="xs:string"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <!--  type for message digest type -->
  <xs:simpleType name="digestTypeType">
    <xs:restriction base="xs:string">
      <xs:whiteSpace value="collapse"/>
      <xs:enumeration value="MD5"/>
      <xs:enumeration value="SHA-1"/>
      <xs:enumeration value="SHA-256"/>
    </xs:restriction>
  </xs:simpleType>
  <!-- date type between 0001 and 9999 restricted to UTC -->
  <xs:simpleType name="dateType">
    <xs:restriction base="xs:date">
      <xs:minInclusive value="0001-01-01Z"/>
      <xs:maxExclusive value="10000-01-01Z"/>
      <xs:pattern value="\d{4}-\d{2}-\d{2}Z?"/>
    </xs:restriction>
  </xs:simpleType>
  <!-- time type restricted to UTC -->
  <xs:simpleType name="timeType">
    <xs:restriction base="xs:time">
      <xs:pattern value="\d{2}:\d{2}:\d{2}(\.\d+)?Z?"/>
    </xs:restriction>
  </xs:simpleType>
  <!-- dateTime type between 0001 and 9999 restricted to UTC -->
  <xs:simpleType name="dateTimeType">
    <xs:restriction base="xs:dateTime">
      <xs:minInclusive value="0001-01-01T00:00:00.000000000Z"/>
      <xs:maxExclusive value="10000-01-01T00:00:00.000000000Z"/>
      <xs:pattern value="\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?Z?"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== DILCISBoard/SIARD/SIARD 2.0/format/2015-10-27/table0.xml
<?xml version="1.0" encoding="utf-8"?>
<table 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xmlns="http://www.admin.ch/xmlns/siard/2.0/schema0/table0.xsd" 
  xsi:schemaLocation="http://www.admin.ch/xmlns/siard/2.0/schema0/table0.xsd table0.xsd">
  <row>
  
    <c1>true</c1> <!-- CBOOLEAN -->
    <c2>01</c2> <!-- CBIT -->
    <c3>31323334</c3> <!-- CBIT_32 -->
    <c4>1E1F2021222324252627282930313233</c4> <!-- CBIT_VARYING_160 -->
    <c5>1E</c5> <!-- CBINARY -->
    <c6>1E1F202122</c6> <!-- CBINARY_5 -->
    <c7>1E1F2021222324252627</c7> <!-- CBINARY_VARYING_32 -->
    <c8 file="record0.bin" length="16000" digestType="MD5" messageDigest="D1C411FC45542DCA86EEB1CC9B4B596C" /> <!-- CBINARY_LARGE_OBJECT -->
    <c9>A</c9> <!-- CCHARACTER -->
    <c10>ABCDE</c10> <!-- CCHARACTER_5 -->
    <c11>A varchar(32) text</c11> <!-- CCHARACTER_VARYING_32 -->
    <c12 file="record0.txt" length="84000" digestType="MD5" messageDigest="D1341187455adfCA86E5666C974B5950"/> <!-- CCHARACTER_LARGE_OBJECT -->
    <c13>Ä</c13> <!-- CNATIONAL_CHARACTER -->
    <c14>ABCDÖ</c14> <!-- CNATIONAL_CHARACTER_5 -->
    <c15>A national varchar(32) text</c15> <!-- CNATIONAL_CHARACTER_VARYING -->
    <c16 file="record0.txt" length="84000" digestType="MD5" messageDigest="243561FE455EBFCAA1256667774B5831" /> <!-- CNATIONAL_CHARACTER_LARGE_OBJECT -->
    <c17 file="record0.xml" length="10424" digestType="MD5" messageDigest="5234Fd874EFADFCA86E5CDDC97398991" /> <!-- CXML -->
    <c18>4321</c18> <!-- SMALLINT -->
    <c19>5</c19> <!-- CINTEGER -->
    <c20>98765432101234</c20> <!-- CBIGINT -->
    <c21>12345</c21> <!-- CDECIMAL -->
    <c22>123</c22> <!-- CDECIMAL_3 -->
    <c23>123.45</c23> <!-- CDECIMAL_5_2 -->
    <c24>54321</c24> <!-- NUMERIC -->
    <c25>123</c25> <!-- NUMERIC_3 -->
    <c26>123.45</c26> <!-- NUMERIC_5_2 -->
    <c27>3.14159</c27> <!-- CREAL -->
    <c28>3.14159</c28> <!-- CFLOAT -->
    <c29>3.141</c29> <!-- CFLOAT_13 -->
    <c30>987654321.0900</c30> <!-- CDOUBLE_PRECISION -->
    <c31>2013-10-18</c31> <!-- CDATE -->
    <c32>17:24:33</c32> <!-- CTIME -->
    <c33>17:24:33.12345</c33> <!-- CTIME_5 -->
    <c34>2011-12-05T16:24:33.123456</c34> <!-- CTIMESTAMP -->
    <c35>2011-12-05T16:24:33.1234567</c35> <!-- CTIMESTAMP_7 -->
  </row>
</table>
